Revert "Improve error reporting"
Causes cyclic import. Too lazy too fix now.

Traceback (most recent call last):
  File "Z:\kderoot\emerge\bin\EmergeSetupHelper.py", line 9, in <module>
    from EmergeConfig import *
  File "Z:\kderoot\emerge\bin\EmergeConfig.py", line 23, in <module>
    import utils
  File "Z:\kderoot\emerge\bin\utils.py", line 63, in <module>
    WGetExecutable = os.path.join( EmergeStandardDirs.emergeRoot(), "bin", "wget.exe" )
NameError: name 'EmergeStandardDirs' is not defined

This reverts commit 2b83b276dd7a788dc92d9e0acbf39b15eb9f4d50.